version: '2.0'

services:
  web:
    build: ./evopie
    volumes:
      - /EvoPIE/EvoPIE-INSTALLATION-FOLDER-NAME-GOES-HERE/data:/app/data
    environment:
      - EVOPIE_DATABASE_URI=sqlite:////app/data/db.sqlite
    expose:
      - 5000
    env_file:
      - ./evopie/.env.dev
    restart: always
  nginx:
    build: ./nginx
    ports:
      - "443:443"
      - "9443:9443"
    depends_on:
      - web
    restart: always
    volumes:
      - /etc/letsencrypt/live/evopie.cse.usf.edu:/etc/certs

    