version: '2.0'

services:
  web:
    build: ./evopie
    volumes:
      - /EvoPIE-INSTALLATION-FOLDER-NAME-GOES-HERE/DB_quizlib.sqlite:/app/EvoPIE/evopie/DB_quizlib.sqlite
    expose:
      - 5000
    env_file:
      - ./evopie/.env.dev
    restart: always
  nginx:
    build: ./nginx
    ports:
      - "5000:80"
    depends_on:
      - web
    restart: always
    