services:
  updater:
    build: ./analysislayer
    volumes:
      - ${EVOPIE_DATA_DIR:-./data}:/app/data
    environment:
      - EVOPIE_DATABASE_URI=${EVOPIE_DATABASE_URI:-sqlite:////app/data/db.sqlite}
      - INIT_DB=1
    expose:
      - 5000
    env_file:
      - ./analysislayer/.env.dev
    restart: always
  web:
    build: ./evopie
    volumes:
      - ${EVOPIE_DATA_DIR:-./data}:/app/data
    environment:
      - EVOPIE_DATABASE_URI=${EVOPIE_DATABASE_URI:-sqlite:////app/data/db.sqlite}
    expose:
      - 5000
    env_file:
      - ./evopie/.env.dev
    depends_on:
      - updater      
    restart: always
  nginx:
    build: ./nginx
    ports:
      - "5000:5000"
    depends_on:
      - web
    restart: always
    volumes:
      - ${EVOPIE_CERTS_DIR:-/etc/letsencrypt}:/etc/nginx/certs