version: '3.7'

services:
  web:
    build: ./web
    volumes:
      - /mnt/c/Users/aless/OneDrive/Desktop/dev/github/EvoPIE/evopie/DB_quizlib.sqlite:/app/EvoPIE/evopie/DB_quizlib.sqlite
    expose:
      - 5000
    env_file:
      - ./web/.env.dev
  nginx:
    build: ./nginx
    ports:
      - "5000:80"
    depends_on:
      - web